services:
  express:
    image: ghcr.io/alexispet/final-test-alan-crts/express-app:main
    depends_on:
      - mariadb
    environment:
      - DB_HOST: ${DB_HOST}
      - DB_USER: ${DB_USER}
      - DB_PASSWORD: ${DB_PASSWORD}
      - DB_DATABASE: ${DB_DATABASE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.express-prod.rule=Host(`ec2-54-172-119-210.compute-1.amazonaws.com`)"
      - "traefik.http.routers.express-prod.entrypoints=websecure"
      - "traefik.http.routers.express-prod.tls.certresolver=myresolver"
  mariadb:
    image: mariadb:11.2.2
    environment:
      - MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${DB_DATABASE}
      - MYSQL_USER: ${DB_USER}
      - MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql