- name: Update web server
  hosts: webservers
  remote_user: admin
  become: true
  become_method: sudo

  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Installation des dépendances de Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common

    - name: Ajout de la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: Ajout du référentiel Docker
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Mise à jour des paquets après l'ajout du référentiel Docker
      apt:
        update_cache: yes

    - name: Installation de Docker
      apt:
        name: docker-ce
        state: present

    - name: Démarrage du service Docker
      service:
        name: docker
        state: started

    - name: Ajout de l'utilisateur au group docker
      user:
        name: admin
        groups: docker
        append: yes

    - name: vérifier le statut de docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: création du fichier de l'environnement
      file:
        path: "/home/admin/{{ env }}"
        state: directory
        owner: admin
        group: admin
        mode: '0755'
    - name: create files
      file:
        path: "/home/admin/{{ env }}/.env"
        state: touch
        owner: admin
        group: admin
        mode: '0755'
    - name: send by scp docker-compose file to remote host
      copy:
        src: /home/runner/work/final-test-alan-crts/final-test-alan-crts/docker-compose.global.yml
        dest: /home/admin/docker-compose.global.yml
        owner: admin
        group: admin
        mode: '0755'
    - name: send by scp docker-compose file to remote host
      copy:
        src: /home/runner/work/final-test-alan-crts/final-test-alan-crts/docker-compose.{{ env }}.yml
        dest: /home/admin/{{ env }}/docker-compose.{{ env }}.yml
        owner: admin
        group: admin
        mode: '0755'
    - name: run docker-compose
      command: docker compose -f /home/admin/docker-compose.global.yml up -d
      args:
        chdir: /home/admin
    - name: run docker-compose
      command: docker compose -f /home/admin/{{ env }}/docker-compose.{{ env }}.yml up -d
      args:
        chdir: /home/admin/{{ env }}