name: ansible
on: [workflow_dispatch]

jobs:
    triger-ansible:
        environment: ${{ github.ref_name }}
        runs-on: ubuntu-latest
        if: github.ref_name == 'dev' || github.ref_name == 'main'
        steps:
            - name: Checkout
              uses: actions/checkout@v4  
              
            - name: Run playbook
              uses: dawidd6/action-ansible-playbook@v2
              with:
                playbook: playbook.yml
                inventory: inventory.ini
                directory: ./ansible
                key: ${{secrets.SSH_PRIVATE_KEY}}
                options:
                    --inventory inventory.ini
                    -e env=${{github.ref_name}}
                    -e DB_HOST=${{secrets.DB_HOST}}
                    -e DB_USER=${{secrets.DB_USER}}
                    -e DB_PASSWORD=${{secrets.DB_PASSWORD}}
                    -e DB_DATABASE=${{secrets.DB_DATABASE}}
                    
            - name: Shoutrrr
              uses: containrrr/shoutrrr-action@v1
              with:
                url: ${{ secrets.DISCORD_WEBHOOK }}
                title: Deployed on server ${{github.ref_name}}
                message: server ${{github.ref_name}} as been setup and deployed