name: build
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:    
  tests:
    environment: dev
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
    steps:
      - uses: actions/checkout@v4
      - name: Wait for the app to start
        run: docker compose up -d --wait --build
      - name: Run tests
        run: docker compose exec express npm run test
  

  security:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  eslint:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
          
  build-prod:
    runs-on: ubuntu-latest
    needs: [security, eslint]
    environment:
      name: main
      url: https://cesi-prod.alan-courtois.fr/
    if: github.ref_name == 'main'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/express-app

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: express
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-dev:
      runs-on: ubuntu-latest
      needs: [security, eslint]
      environment:
        name: dev
        url: https://cesi-dev.alan-courtois.fr/
      if: github.ref_name == 'dev'
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/express-app

        - name: Build and push Docker image
          uses: docker/build-push-action@v5
          with:
            context: .
            target: express
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}