name: Lighthouse CI
on:
    schedule:
        - cron: '0 0 * * *'
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://cesi.alan-courtois.fr,https://cesi.alan-courtois.fr/post'